### ISSUE TITLE
Feature Request: Enclosure should start up with lights on by default

### ISSUE THREAD

**Issue by Galindorf** [Snapmaker/Snapmaker2-Controller#122] opened 2021-06-07 23:57 UTC
# 🐞 feature request

### Is your feature request related to a problem? Please describe.

On startup, enclosure lights are automatically off, they have to be turned on manually in an awkward fashion on a separate screen of the touch pad. 
### Describe the solution you'd like?
When the Snapmaker with enclosure starts up, please have the lights be "on" by default.

**Comment by iamrecursion** [comment] 2021-06-18 07:47
Duplicate of #65.

**Comment by Snapmaker-support** [comment] 2021-08-11 04:27
Hi friend,
The coming new firmware that will support the feature is scheduled to be released this month.

**Comment by scyto** [comment] 2021-09-17 00:28
i can confirm this is fixed, yay! thanks snapmaker. time to close the issue :-)

**Comment by xhycode** [comment] 2022-01-11 02:27
This issue has been supported in [V1.13.2](https://forum.snapmaker.com/t/snapmaker-2-0-firmware-updates-and-downloads/5443/17) and later, please use the latest firmware.

**Closed by xhycode** 2022-01-11 02:27 UTC
Labels: Category: HMI, Category: Enclosure
